[project]
name = "PyCaster"
version = "0.1.0"
description = "Highly un-optimized raycaster in Python and PyGame"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "pygame>=2.6.1",
    "pyright>=1.1.398",
    "ruff>=0.11.5",
]
